// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    copy: typeof import("./components/InputCurrency copy.vue")["default"];
    HelloWorld: typeof import("./components/HelloWorld.vue")["default"];
    InputAmount: typeof import("./components/InputAmount.vue")["default"];
    InputCurrency: typeof import("./components/InputCurrency.vue")["default"];
    InputValue: typeof import("./components/InputValue.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheForm: typeof import("./components/TheForm.vue")["default"];
    TheHeader: typeof import("./components/TheHeader.vue")["default"];
  }
}
